---
name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install

      - name: Install ESLint 8.x
        run: npm install eslint@8.45.0

      - name: Lint code
        run: npx eslint . --no-error-on-unmatched-pattern
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: . # Path to the directory containing your Dockerfile
          file: ./Dockerfile # Path to your Dockerfile
          tags: korneelgrumieau/webapp:latest # Tag for the Docker image
          push: false # Do not push the image yet
